STAT 3255 Final Project Proposal --
Colin Sullivan
---

# Introduction
Affordable housing has become a hot-topic discussion point in many towns across Connecticut, including my own hometown of Fairfield. As certain counties continue to price out 
even people of relatively high net worth, town officials have often turned to proposals of newly built affordable housing complexes. More often than not, the public reaction 
to said proposals is negative, with citizens citing generally prejudiced opinions about how new affordable housing will affect town safety and income levels. There have been 
some nationwide research done on the subject, but very little at the level of the state of Connecticut.

# Specific Aims
I wish to do some research into the effects of affordable housing on Connecticut, at the town, county, and state level, particularly on town income and on town crime. I also want to 
look at census data to see if there is an effect in population as affordable housing is increased or decreased by town. Specifically, I want to test for correlation between these 
variables and affordable housing. I feel as though the research is important to help towns make educated decisions not based upon prejudices.

# Data Description
There are several different datasets that I will be merging/working with to answer the questions posed. The primary one is the "Affordable Housing by Town 2011-2022" dataset, which 
contains columns telling the town and various statistics about affordable housing in that town, and there are 2,025 rows of data. I will be combining this data with "Uniform 
Crime Reporting System Arrests" data. Each arrest dataset is for one calendar year, so I will have to download one for each year. These datasets are ugly, with poorly named and 
distributed columns, so they will need to be significantly cleaned up. I will also be combining this data with the CT census data for town populations over each year, and finally I will 
be using a dataset showing income tax per town per year to help determine town income levels. All of these datasets come from CT Data websites.

# Research Design/Methods
The data will need significant cleaning and manipulation to get into a useable state, and I hope to combine it all into one dataframe that I can work easily with, although perhaps 
separated by year. I will modify this based upon need as I progress in the project. I want to focus on helpful visualizations of the data. Unfortunately, the crime data does not come 
with specific locations for each row, but since they are in towns I want to show town by town visualizations of Connecticut for affordable housing levels, crime levels, income levels, 
etc. I hope to use hypothesis testing (t-tests and ANOVA) for exploratory data analysis, and I'd like the brunt of my statistical methods to be based upon linear regression to check for 
correlation strength between the variables and to provide some forecasting predictions.

# Discussion
I hope that my research finds that an increase in affordable housing does not lead to an increase in negative statistics about a town, however I am unsure and there may be some truth 
to the naysayers' arguments against the policies. I think regardless of the outcome, the research will add some useful information to the ongoing discussions statewide and hopefully 
the conclusions of correlation and forecasting can have positive impacts on policy decisions, even if the outcome is not exactly what I expect.

# Conclusion
To summarize, I wish to try and dispel common misconceptions about affordable housing in the state of Connecticut and any negative drawbacks that people tend to assume comes along 
with said housing. Through my research and data manipulation, I believe this can add positive contextual information to the frequent discussions on the topic.